// src/client/import-dialog/Dialog.tsx
import { useState } from 'react';
import { Application } from '../Application';
import { PreviewTable } from './components/PreviewTable';
import { Typography, Box, Tabs, Tab } from '@mui/material';
import { ImportForm } from './components/ImportForm';
import {
  ImportContextProvider,
  useImportContext,
} from './context/import-context';
import { DataTable } from './components/DataTable';

const RawTable = () => {
  const { importData } = useImportContext();

  return (
    importData && (
      <DataTable table={importData} options={{ selectable: true }} />
    )
  );
};

export const Dialog = () => {
  const [activeTab, setActiveTab] = useState(0);
  const [statusText, setStatusText] = useState<string>('-');

  return (
    <Application>
      <ImportContextProvider
        statusText={statusText}
        setStatusText={setStatusText}
      >
        <ImportForm />
        <Typography variant="body1" mb={2}>
          {statusText}
        </Typography>
        <Tabs
          value={activeTab}
          onChange={(_event, newActiveTab) => setActiveTab(newActiveTab)}
        >
          <Tab label="Raw Data" />
          <Tab label="Import Preview" />
        </Tabs>
        <Box
          mt={2}
          style={{ display: activeTab === 0 ? 'block' : 'none' }}
          className="tab col s3"
          id={`raw-input-table`}
        >
          <RawTable />
        </Box>
        <Box
          mt={2}
          style={{ display: activeTab === 1 ? 'block' : 'none' }}
          className="tab col s3"
          id={`import-preview-table`}
        >
          <PreviewTable />
        </Box>
      </ImportContextProvider>
    </Application>
  );
};

// src/client/import-dialog/Dialog.svelte
<script lang="ts">
  import type { Table } from '@/common/types';
  import { Tabs, TabItem } from 'flowbite-svelte';
  import Application from '../Application.svelte';
  import ImportForm from '../components/ImportForm.svelte';
  import { appState } from '../states/app.svelte';
  import { importState } from '../states/import.svelte';
  import DataTable from '../components/DataTable.svelte';
  import PreviewTable from '../components/PreviewTable.svelte';
</script>

{#snippet rawTable(importData: Table)}
  <DataTable table={importData} options={{ selectable: true }} />
{/snippet}

<Application>
  <ImportForm />

  <p class="text-base my-2">
    {appState.statusText}
  </p>

  <Tabs tabStyle="underline" contentClass="p-0">
    <TabItem open id="raw-input-table" title="Raw Data">
      {#if importState.importData}
        {@render rawTable(importState.importData)}
      {/if}
    </TabItem>
    <TabItem title="Import Preview">
      <PreviewTable />
    </TabItem>
  </Tabs>
</Application>
