// .storybook/dialog-decorator.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import styles from './dialog.module.css';
  
  let { children, size, title }: {
    children: Snippet,
    size: [number, number]
    title: string
  } = $props();

  const [width, height] = size ?? [900, 600];
</script>

<div class={styles.dialog}>
  <div class={styles.dialog__heading}>
    <span class={styles.dialog__heading__title}>
      {title}
    </span>
    <span class={styles.dialog__heading__close}></span>
  </div>
  <div class={styles.dialog__content} style:width={`${width}px`} style:height={`${height}px`}>
    {@render children()}
  </div>
</div>

// .storybook/dialog-decorator.tsx
import { ReactRenderer } from '@storybook/react';
import { DecoratorFunction } from '@storybook/types';

import styles from './dialog.module.css';

type DialogDecoratorArgs = {
  dialogSize?: [number, number];
  dialogTitle?: string;
};

export const DialogDecorator: DecoratorFunction<
  ReactRenderer,
  DialogDecoratorArgs
> = (Story, { args, title: storyTitle }) => {
  const [width, height] = args?.dialogSize ?? [900, 600];

  return (
    <div className={styles.dialog}>
      <div className={styles.dialog__heading}>
        <span className={styles.dialog__heading__title}>
          {args.dialogTitle ?? storyTitle}
        </span>
        <span className={styles.dialog__heading__close}></span>
      </div>
      <div style={{ width, height }}>
        <Story />
      </div>
    </div>
  );
};
