// src/client/Application.svelte
<script lang="ts">
  let { children } = $props()

  // const theme = createTheme({
  //   palette: {
  //     primary: {
  //       main: green[800],
  //     },
  //     secondary: blue,
  //   },
  //   components: {
  //     MuiButton: {
  //       defaultProps: {
  //         disableRipple: true,
  //       },
  //     },
  //     MuiTextField: {
  //       defaultProps: {
  //         size: 'small',
  //       },
  //     },
  //   },
  // });

  // return (
  //   <ScopedCssBaseline>
  //     <ThemeProvider theme={theme}>{children}</ThemeProvider>
  //   </ScopedCssBaseline>
  // );
</script>

{@render children?.()}

// src/client/Application.tsx
import { ScopedCssBaseline, ThemeProvider, createTheme } from '@mui/material';
import { blue, green } from '@mui/material/colors';
import { ReactNode } from 'react';

export const Application = ({ children }: { children: ReactNode }) => {
  const theme = createTheme({
    palette: {
      primary: {
        main: green[800],
      },
      secondary: blue,
    },
    components: {
      MuiButton: {
        defaultProps: {
          disableRipple: true,
        },
      },
      MuiTextField: {
        defaultProps: {
          size: 'small',
        },
      },
    },
  });

  return (
    <ScopedCssBaseline>
      <ThemeProvider theme={theme}>{children}</ThemeProvider>
    </ScopedCssBaseline>
  );
};
